### ISSUE TITLE
Support the DAT ecosystem

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-plugin-data#4]
The dat-data.com project abstracts streaming data interfaces and data version control. `wiki` tries to [_wrap data with visualization_](http://fed.wiki.org/welcome-visitors.html), which implies data mangling.

Dat is supported by @maxogden and seems to develop into a modular ETL engine for distributed [(micro)service-oriented architectures](http://h2020.wiki.allmende.io/view/requirements/view/prequisites/view/open-ecosystems). Now the federation comes into play. The following just came to my mind:

---

[Wiki's drag-and-drop workflow](https://github.com/WardCunningham/Smallest-Federated-Wiki/issues/409) could offer easy instantiation of new **dat**s for a [karissa/dathub](https://github.com/karissa/dathub) (_pinging_ @karissa) for example, by offering a compatible ReadWrite API.

Experiments in this regard could mean to
- [ ] offer [Newline Delimited JSON](http://ndjson.org/) support for import and export in `wiki-plugin-data`. (_pinging_ @finnp)
- [ ] streamline ReadWriteWeb APIs both offer
  - in terms of
    - authorization or
    - the semantics and vocabulary of shared endpoints and,
      - where this plugin may offer additional ones,
  - maybe [later even esp.](https://github.com/WardCunningham/Smallest-Federated-Wiki/issues/411) in regards of the [Linked Data Platform and wiki](https://github.com/WardCunningham/Smallest-Federated-Wiki/issues/409#issuecomment-45581212) and [generalized Hydra](http://www.hydra-cg.com/)s. (_pinging_ @bblfish)
- share thoughts on
  - [ ] backend-agnostic storage workflows.
  - [ ] [distributed versioning](http://wiki-allmende.rhcloud.com/view/wiki-version-control/view/wik-dvcs/view/json-schema) and [maybe patch](https://github.com/WardCunningham/Smallest-Federated-Wiki/wiki/Federation-Details)-[based versioning](http://wiki-allmende.rhcloud.com/view/wiki-version-control/view/wik-dvcs/view/semanticize-wik/view/socialize-wik/view/wik-architecture/view/wik-transport/view/wik-storage) infrastructures. (_pinging_ @rynomad)
  - [ ] federated Publish-Subscribe (Merge/Fork) scenarios.

**Comment by WardCunningham** [comment]
I would like to see how wiki and dat could work together. I could imagine a dat plugin that exposed dat data to other pages much like the data plugin but without taking on full responsibility for the dat data. The idea would be to move a wiki near the dat rather than move the dat to the wiki. Results from specific analysis could be cached on a page that travels. Someone who wanted an update would have to rummage through the journal to find the source and return there. Or they could take on duplicating the dat in their environment and running their queries locally.

**Comment by almereyda** [comment]
Since there is a sneak peek of how such an integration could look like, i.e. forked to https://github.com/federated-wiki/wiki-plugin-datscript, we know that wiki can be an interface to Dat and its pipelining environment.
Both environments store their data with content addressable items. Both evaluate IPFS as an option for their storage backend. Each of these three components aid their users in exposing valuable interfaces for data transmission, storage and visualisation.
Once web surfers get used to be interacting with a vast diversity of interlinked interfaces, these three can act as pioneers to show how unixoid composeability translates to the Web Platform.

**Comment by almereyda** [comment]
@paul90 meanwhile maintains a [`wiki-client-dat-variant`](https://github.com/paul90/wiki-client-dat-variant).
